// ── Skill Database ───────────────────────────────────────────────────────────
// name, category, aliases, demand (1-5), avgSalaryBoost (LPA), difficulty (1-5)

export const SKILL_DB = [
  // Frontend
  {
    name: 'React',
    category: 'Frontend',
    aliases: ['reactjs', 'react.js'],
    demand: 5,
    avgSalaryBoost: 4,
    difficulty: 3,
  },
  {
    name: 'Vue',
    category: 'Frontend',
    aliases: ['vuejs', 'vue.js'],
    demand: 3,
    avgSalaryBoost: 3,
    difficulty: 2,
  },
  {
    name: 'Angular',
    category: 'Frontend',
    aliases: ['angularjs'],
    demand: 3,
    avgSalaryBoost: 3.5,
    difficulty: 4,
  },
  {
    name: 'Next.js',
    category: 'Frontend',
    aliases: ['nextjs', 'next js'],
    demand: 5,
    avgSalaryBoost: 4.5,
    difficulty: 3,
  },
  {
    name: 'TypeScript',
    category: 'Frontend',
    aliases: ['ts', 'typescript'],
    demand: 5,
    avgSalaryBoost: 4,
    difficulty: 3,
  },
  {
    name: 'JavaScript',
    category: 'Frontend',
    aliases: ['js', 'javascript', 'es6', 'ecmascript'],
    demand: 5,
    avgSalaryBoost: 3,
    difficulty: 2,
  },
  {
    name: 'HTML',
    category: 'Frontend',
    aliases: ['html5'],
    demand: 5,
    avgSalaryBoost: 1,
    difficulty: 1,
  },
  {
    name: 'CSS',
    category: 'Frontend',
    aliases: ['css3', 'scss', 'sass', 'less'],
    demand: 5,
    avgSalaryBoost: 1.5,
    difficulty: 2,
  },
  {
    name: 'Tailwind CSS',
    category: 'Frontend',
    aliases: ['tailwind', 'tailwindcss'],
    demand: 4,
    avgSalaryBoost: 2.5,
    difficulty: 1,
  },
  {
    name: 'Redux',
    category: 'Frontend',
    aliases: ['redux toolkit', 'zustand', 'recoil'],
    demand: 3,
    avgSalaryBoost: 2,
    difficulty: 3,
  },
  {
    name: 'Testing',
    category: 'Frontend',
    aliases: ['jest', 'react testing library', 'vitest'],
    demand: 3,
    avgSalaryBoost: 2,
    difficulty: 3,
  },
  {
    name: 'Webpack',
    category: 'Frontend',
    aliases: ['vite', 'rollup', 'parcel'],
    demand: 2,
    avgSalaryBoost: 1.5,
    difficulty: 3,
  },
  {
    name: 'GraphQL',
    category: 'Frontend',
    aliases: ['apollo', 'relay'],
    demand: 3,
    avgSalaryBoost: 3,
    difficulty: 3,
  },
  {
    name: 'REST API',
    category: 'Frontend',
    aliases: ['rest', 'restful', 'api', 'http'],
    demand: 5,
    avgSalaryBoost: 2,
    difficulty: 2,
  },
  {
    name: 'Svelte',
    category: 'Frontend',
    aliases: ['sveltekit'],
    demand: 2,
    avgSalaryBoost: 2.5,
    difficulty: 2,
  },

  // Backend
  {
    name: 'Node.js',
    category: 'Backend',
    aliases: ['nodejs', 'node js'],
    demand: 5,
    avgSalaryBoost: 4,
    difficulty: 3,
  },
  {
    name: 'Express',
    category: 'Backend',
    aliases: ['expressjs', 'express.js'],
    demand: 4,
    avgSalaryBoost: 3,
    difficulty: 2,
  },
  {
    name: 'Django',
    category: 'Backend',
    aliases: ['django rest framework', 'drf'],
    demand: 3,
    avgSalaryBoost: 3.5,
    difficulty: 3,
  },
  {
    name: 'FastAPI',
    category: 'Backend',
    aliases: ['fastapi'],
    demand: 3,
    avgSalaryBoost: 3.5,
    difficulty: 2,
  },
  {
    name: 'Spring Boot',
    category: 'Backend',
    aliases: ['spring', 'springboot', 'java spring'],
    demand: 3,
    avgSalaryBoost: 4,
    difficulty: 4,
  },
  {
    name: 'Laravel',
    category: 'Backend',
    aliases: ['php', 'laravel'],
    demand: 2,
    avgSalaryBoost: 2.5,
    difficulty: 3,
  },
  {
    name: 'NestJS',
    category: 'Backend',
    aliases: ['nestjs', 'nest.js'],
    demand: 3,
    avgSalaryBoost: 3.5,
    difficulty: 3,
  },
  {
    name: 'Python',
    category: 'Backend',
    aliases: ['py', 'python3'],
    demand: 5,
    avgSalaryBoost: 4,
    difficulty: 2,
  },
  {
    name: 'Java',
    category: 'Backend',
    aliases: ['java'],
    demand: 3,
    avgSalaryBoost: 3,
    difficulty: 4,
  },
  {
    name: 'Go',
    category: 'Backend',
    aliases: ['golang'],
    demand: 3,
    avgSalaryBoost: 5,
    difficulty: 4,
  },
  {
    name: 'Rust',
    category: 'Backend',
    aliases: ['rust lang'],
    demand: 2,
    avgSalaryBoost: 6,
    difficulty: 5,
  },
  {
    name: 'Ruby',
    category: 'Backend',
    aliases: ['ruby on rails', 'ror'],
    demand: 2,
    avgSalaryBoost: 3,
    difficulty: 3,
  },
  {
    name: 'PHP',
    category: 'Backend',
    aliases: ['php'],
    demand: 2,
    avgSalaryBoost: 2,
    difficulty: 2,
  },
  {
    name: 'C#',
    category: 'Backend',
    aliases: ['csharp', 'dotnet', '.net', 'asp.net'],
    demand: 3,
    avgSalaryBoost: 3.5,
    difficulty: 4,
  },

  // Database
  {
    name: 'MongoDB',
    category: 'Database',
    aliases: ['mongo'],
    demand: 4,
    avgSalaryBoost: 2.5,
    difficulty: 2,
  },
  {
    name: 'PostgreSQL',
    category: 'Database',
    aliases: ['postgres', 'psql'],
    demand: 4,
    avgSalaryBoost: 3,
    difficulty: 3,
  },
  {
    name: 'MySQL',
    category: 'Database',
    aliases: ['sql', 'mysql'],
    demand: 4,
    avgSalaryBoost: 2,
    difficulty: 2,
  },
  {
    name: 'Redis',
    category: 'Database',
    aliases: ['redis cache'],
    demand: 3,
    avgSalaryBoost: 2.5,
    difficulty: 2,
  },
  {
    name: 'Firebase',
    category: 'Database',
    aliases: ['firestore', 'firebase realtime'],
    demand: 3,
    avgSalaryBoost: 2,
    difficulty: 2,
  },
  {
    name: 'Supabase',
    category: 'Database',
    aliases: ['supabase'],
    demand: 3,
    avgSalaryBoost: 2.5,
    difficulty: 2,
  },
  {
    name: 'Prisma',
    category: 'Database',
    aliases: ['prisma orm'],
    demand: 3,
    avgSalaryBoost: 2,
    difficulty: 2,
  },
  {
    name: 'Elasticsearch',
    category: 'Database',
    aliases: ['elastic search', 'opensearch'],
    demand: 2,
    avgSalaryBoost: 3,
    difficulty: 4,
  },
  {
    name: 'SQLite',
    category: 'Database',
    aliases: ['sqlite'],
    demand: 2,
    avgSalaryBoost: 1,
    difficulty: 1,
  },
  {
    name: 'DynamoDB',
    category: 'Database',
    aliases: ['dynamodb', 'aws dynamodb'],
    demand: 2,
    avgSalaryBoost: 3,
    difficulty: 3,
  },

  // DevOps
  {
    name: 'Docker',
    category: 'DevOps',
    aliases: ['containerization', 'containers'],
    demand: 5,
    avgSalaryBoost: 4,
    difficulty: 3,
  },
  {
    name: 'Kubernetes',
    category: 'DevOps',
    aliases: ['k8s', 'k8'],
    demand: 4,
    avgSalaryBoost: 5,
    difficulty: 5,
  },
  {
    name: 'AWS',
    category: 'DevOps',
    aliases: ['amazon web services', 'aws cloud'],
    demand: 5,
    avgSalaryBoost: 5,
    difficulty: 4,
  },
  {
    name: 'GCP',
    category: 'DevOps',
    aliases: ['google cloud', 'google cloud platform'],
    demand: 3,
    avgSalaryBoost: 4.5,
    difficulty: 4,
  },
  {
    name: 'Azure',
    category: 'DevOps',
    aliases: ['microsoft azure'],
    demand: 3,
    avgSalaryBoost: 4.5,
    difficulty: 4,
  },
  {
    name: 'GitHub Actions',
    category: 'DevOps',
    aliases: ['ci/cd', 'cicd', 'github actions'],
    demand: 4,
    avgSalaryBoost: 3,
    difficulty: 3,
  },
  {
    name: 'Jenkins',
    category: 'DevOps',
    aliases: ['jenkins ci'],
    demand: 2,
    avgSalaryBoost: 2.5,
    difficulty: 3,
  },
  {
    name: 'Nginx',
    category: 'DevOps',
    aliases: ['nginx'],
    demand: 3,
    avgSalaryBoost: 2,
    difficulty: 3,
  },
  {
    name: 'Linux',
    category: 'DevOps',
    aliases: ['ubuntu', 'bash', 'shell', 'unix'],
    demand: 4,
    avgSalaryBoost: 2.5,
    difficulty: 3,
  },
  {
    name: 'Terraform',
    category: 'DevOps',
    aliases: ['iac', 'infrastructure as code'],
    demand: 3,
    avgSalaryBoost: 4,
    difficulty: 4,
  },
  {
    name: 'Git',
    category: 'DevOps',
    aliases: ['github', 'gitlab', 'version control'],
    demand: 5,
    avgSalaryBoost: 1,
    difficulty: 1,
  },
  {
    name: 'Ansible',
    category: 'DevOps',
    aliases: ['ansible'],
    demand: 2,
    avgSalaryBoost: 3,
    difficulty: 3,
  },
  {
    name: 'Prometheus',
    category: 'DevOps',
    aliases: ['grafana', 'monitoring', 'observability'],
    demand: 2,
    avgSalaryBoost: 3,
    difficulty: 3,
  },

  // AI-ML
  {
    name: 'TensorFlow',
    category: 'AI-ML',
    aliases: ['tensorflow', 'tf'],
    demand: 4,
    avgSalaryBoost: 5,
    difficulty: 4,
  },
  {
    name: 'PyTorch',
    category: 'AI-ML',
    aliases: ['pytorch', 'torch'],
    demand: 4,
    avgSalaryBoost: 5.5,
    difficulty: 4,
  },
  {
    name: 'Scikit-learn',
    category: 'AI-ML',
    aliases: ['sklearn', 'scikit learn'],
    demand: 4,
    avgSalaryBoost: 4,
    difficulty: 3,
  },
  {
    name: 'Pandas',
    category: 'AI-ML',
    aliases: ['pandas'],
    demand: 4,
    avgSalaryBoost: 3,
    difficulty: 2,
  },
  {
    name: 'NumPy',
    category: 'AI-ML',
    aliases: ['numpy'],
    demand: 4,
    avgSalaryBoost: 2.5,
    difficulty: 2,
  },
  {
    name: 'OpenAI API',
    category: 'AI-ML',
    aliases: ['openai', 'chatgpt api', 'gpt'],
    demand: 5,
    avgSalaryBoost: 5,
    difficulty: 2,
  },
  {
    name: 'LangChain',
    category: 'AI-ML',
    aliases: ['langchain'],
    demand: 4,
    avgSalaryBoost: 5,
    difficulty: 3,
  },
  {
    name: 'HuggingFace',
    category: 'AI-ML',
    aliases: ['hugging face', 'transformers'],
    demand: 3,
    avgSalaryBoost: 4.5,
    difficulty: 3,
  },
  {
    name: 'Statistics',
    category: 'AI-ML',
    aliases: ['statistics', 'statistical analysis', 'probability'],
    demand: 3,
    avgSalaryBoost: 3,
    difficulty: 3,
  },
  {
    name: 'Deep Learning',
    category: 'AI-ML',
    aliases: ['deep learning', 'neural networks', 'nn'],
    demand: 4,
    avgSalaryBoost: 5,
    difficulty: 5,
  },
  {
    name: 'NLP',
    category: 'AI-ML',
    aliases: ['natural language processing', 'text mining'],
    demand: 3,
    avgSalaryBoost: 4.5,
    difficulty: 4,
  },
  {
    name: 'Computer Vision',
    category: 'AI-ML',
    aliases: ['cv', 'image recognition', 'opencv'],
    demand: 3,
    avgSalaryBoost: 4.5,
    difficulty: 4,
  },
  {
    name: 'MLOps',
    category: 'AI-ML',
    aliases: ['mlops', 'ml pipeline'],
    demand: 3,
    avgSalaryBoost: 5,
    difficulty: 4,
  },
  {
    name: 'SQL',
    category: 'AI-ML',
    aliases: ['sql queries', 'database queries'],
    demand: 4,
    avgSalaryBoost: 2,
    difficulty: 2,
  },

  // Mobile
  {
    name: 'React Native',
    category: 'Mobile',
    aliases: ['react native', 'rn'],
    demand: 3,
    avgSalaryBoost: 3.5,
    difficulty: 3,
  },
  {
    name: 'Flutter',
    category: 'Mobile',
    aliases: ['flutter', 'dart'],
    demand: 3,
    avgSalaryBoost: 3.5,
    difficulty: 3,
  },
  {
    name: 'Swift',
    category: 'Mobile',
    aliases: ['swift', 'ios', 'ios development'],
    demand: 3,
    avgSalaryBoost: 4.5,
    difficulty: 4,
  },
  {
    name: 'Kotlin',
    category: 'Mobile',
    aliases: ['kotlin', 'android development', 'android'],
    demand: 3,
    avgSalaryBoost: 4,
    difficulty: 4,
  },
  {
    name: 'Expo',
    category: 'Mobile',
    aliases: ['expo'],
    demand: 2,
    avgSalaryBoost: 2,
    difficulty: 2,
  },

  // Design
  {
    name: 'Figma',
    category: 'Design',
    aliases: ['figma'],
    demand: 4,
    avgSalaryBoost: 2,
    difficulty: 2,
  },
  {
    name: 'UI/UX Design',
    category: 'Design',
    aliases: ['ux', 'ui design', 'user experience', 'user interface'],
    demand: 3,
    avgSalaryBoost: 2.5,
    difficulty: 3,
  },

  // Soft Skills
  {
    name: 'Communication',
    category: 'Soft Skills',
    aliases: ['presentation', 'public speaking'],
    demand: 5,
    avgSalaryBoost: 2,
    difficulty: 2,
  },
  {
    name: 'Problem Solving',
    category: 'Soft Skills',
    aliases: ['critical thinking', 'analytical'],
    demand: 5,
    avgSalaryBoost: 2,
    difficulty: 2,
  },
  {
    name: 'Teamwork',
    category: 'Soft Skills',
    aliases: ['collaboration', 'team player'],
    demand: 5,
    avgSalaryBoost: 1,
    difficulty: 1,
  },
  {
    name: 'Leadership',
    category: 'Soft Skills',
    aliases: ['management', 'mentoring'],
    demand: 3,
    avgSalaryBoost: 3,
    difficulty: 3,
  },
  {
    name: 'Agile',
    category: 'Soft Skills',
    aliases: ['scrum', 'kanban', 'agile methodology'],
    demand: 4,
    avgSalaryBoost: 2,
    difficulty: 2,
  },
];

// ── Role Requirements ────────────────────────────────────────────────────────

export const ROLE_REQUIREMENTS = {
  'Full Stack Developer': [
    'React',
    'Node.js',
    'MongoDB',
    'Express',
    'TypeScript',
    'Docker',
    'Git',
    'REST API',
    'PostgreSQL',
    'HTML',
    'CSS',
    'JavaScript',
  ],
  'Frontend Developer': [
    'React',
    'TypeScript',
    'CSS',
    'HTML',
    'Tailwind CSS',
    'Next.js',
    'Redux',
    'Testing',
    'JavaScript',
    'Git',
    'Figma',
    'REST API',
  ],
  'Backend Developer': [
    'Node.js',
    'PostgreSQL',
    'Docker',
    'Redis',
    'REST API',
    'GraphQL',
    'AWS',
    'Nginx',
    'Linux',
    'Git',
    'Python',
    'Express',
  ],
  'Data Scientist': [
    'Python',
    'Pandas',
    'NumPy',
    'Scikit-learn',
    'TensorFlow',
    'SQL',
    'Statistics',
    'Deep Learning',
    'NLP',
    'Matplotlib',
    'Git',
    'Jupyter',
  ],
  'DevOps Engineer': [
    'Docker',
    'Kubernetes',
    'AWS',
    'GitHub Actions',
    'Linux',
    'Terraform',
    'Nginx',
    'Git',
    'Python',
    'Ansible',
    'Prometheus',
    'Jenkins',
  ],
  'ML Engineer': [
    'Python',
    'PyTorch',
    'TensorFlow',
    'Scikit-learn',
    'MLOps',
    'LangChain',
    'OpenAI API',
    'Pandas',
    'NumPy',
    'Git',
    'Docker',
    'SQL',
  ],
  'Mobile Developer': [
    'React Native',
    'Flutter',
    'JavaScript',
    'TypeScript',
    'Git',
    'REST API',
    'Firebase',
    'Expo',
    'Redux',
    'Testing',
  ],
  'UI/UX Designer': [
    'Figma',
    'UI/UX Design',
    'CSS',
    'HTML',
    'JavaScript',
    'Tailwind CSS',
    'React',
    'Communication',
    'Prototyping',
  ],
};

// ── ROI Scores ───────────────────────────────────────────────────────────────
// ROI = demand * salaryBoost / difficulty (rounded)

export const ROI_SCORES = Object.fromEntries(
  SKILL_DB.map((s) => [s.name, Math.round((s.demand * s.avgSalaryBoost) / s.difficulty)])
);

// ── Course links per skill ────────────────────────────────────────────────────

export const COURSE_LINKS = {
  React: [
    { label: 'React Docs', url: 'https://react.dev' },
    { label: 'Scrimba React', url: 'https://scrimba.com/learn/learnreact' },
  ],
  TypeScript: [{ label: 'TypeScript Handbook', url: 'https://www.typescriptlang.org/docs/' }],
  'Next.js': [{ label: 'Next.js Docs', url: 'https://nextjs.org/docs' }],
  'Node.js': [{ label: 'Node.js Docs', url: 'https://nodejs.org/docs' }],
  Python: [{ label: 'Python.org', url: 'https://docs.python.org/3/' }],
  Docker: [{ label: 'Docker Docs', url: 'https://docs.docker.com' }],
  AWS: [{ label: 'AWS Skill Builder', url: 'https://explore.skillbuilder.aws' }],
  PostgreSQL: [{ label: 'PostgreSQL Tutorial', url: 'https://www.postgresqltutorial.com' }],
  MongoDB: [{ label: 'MongoDB University', url: 'https://learn.mongodb.com' }],
  TensorFlow: [{ label: 'TF Tutorials', url: 'https://www.tensorflow.org/tutorials' }],
  PyTorch: [{ label: 'PyTorch Tutorials', url: 'https://pytorch.org/tutorials' }],
  'Scikit-learn': [{ label: 'Sklearn Docs', url: 'https://scikit-learn.org/stable/tutorial' }],
  Kubernetes: [{ label: 'K8s Docs', url: 'https://kubernetes.io/docs' }],
  Git: [{ label: 'Pro Git Book', url: 'https://git-scm.com/book/en/v2' }],
  GraphQL: [{ label: 'GraphQL.org', url: 'https://graphql.org/learn/' }],
  Redis: [{ label: 'Redis Docs', url: 'https://redis.io/docs' }],
  Flutter: [{ label: 'Flutter Docs', url: 'https://docs.flutter.dev' }],
  Figma: [{ label: 'Figma Learn', url: 'https://help.figma.com/hc/en-us' }],
  LangChain: [{ label: 'LangChain Docs', url: 'https://docs.langchain.com' }],
  'Tailwind CSS': [{ label: 'Tailwind Docs', url: 'https://tailwindcss.com/docs' }],
};

// ── Difficulty / time estimates ───────────────────────────────────────────────

export const TIME_ESTIMATES = {
  1: '1-2 weeks',
  2: '2-4 weeks',
  3: '4-6 weeks',
  4: '6-10 weeks',
  5: '10-16 weeks',
};
